import { lazy } from "react";

import type { ChapterDefinition } from "../types";

export const sht40Chapter: ChapterDefinition = {
  id: "sht40",
  title: "SHT40",
  subtitle: "RH / temperature",
  icon: "Droplets",
  order: 5,
  slides: [
    {
      id: "sht-title",
      title: "SHT40",
      subtitle: "Chapter entry",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/sht-title/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-title/ShtTitleSlide")),
    },
    {
      id: "sht-objectives",
      title: "Objectives",
      subtitle: "Learning goals",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/sht-objectives/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-objectives/ShtObjectivesSlide")),
    },
    {
      id: "sht-rh-basics",
      title: "RH basics",
      subtitle: "%RH definition",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/sht-rh-basics/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-rh-basics/ShtRhBasicsSlide")),
    },
    {
      id: "sht-comfort",
      title: "Comfort zone",
      subtitle: "T × RH chart",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/sht-comfort/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-comfort/ShtComfortSlide")),
    },
    {
      id: "sht-product-overview",
      title: "Product overview",
      subtitle: "Datasheet snapshot",
      mode: "theory",
      section: "product",
      notes: () => import("./slides/sht-product-overview/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-product-overview/ShtProductOverviewSlide")),
    },
    {
      id: "sht-demo-rh",
      title: "Humidity trend",
      subtitle: "Live %RH",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/sht-demo-rh/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-demo-rh/ShtDemoRhSlide")),
    },
    {
      id: "sht-demo-comfort",
      title: "Comfort classifier",
      subtitle: "Live T + RH",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/sht-demo-comfort/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-demo-comfort/ShtDemoComfortSlide")),
    },
    {
      id: "sht-wire-mask",
      title: "Wire mask",
      subtitle: "TEMP · HUM",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/sht-wire-mask/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-wire-mask/ShtWireMaskSlide")),
    },
    {
      id: "sht-studio-node",
      title: "Sensor Studio node",
      subtitle: "Flow ports",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/sht-studio-node/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-studio-node/ShtStudioNodeSlide")),
    },
    {
      id: "sht-summary",
      title: "Summary",
      subtitle: "Course sensors complete",
      mode: "theory",
      section: "close",
      notes: () => import("./slides/sht-summary/notes.md?raw"),
      Component: lazy(() => import("./slides/sht-summary/ShtSummarySlide")),
    },
  ],
};
