/** Short scope labels for inspector card headers — what the section affects, not “this node”. */
export const INSPECTOR_SCOPE_BADGES = {
  config: "Config",
  layout: "Layout",
  display: "Display",
  style: "Style",
  preview: "Preview",
  monitor: "Monitor",
  pins: "Pins",
  runtime: "Runtime",
  analyser: "Analyser",
  binding: "Binding",
  zones: "Zones",
  scene: "Scene",
  graph: "Graph",
  interface: "Interface",
} as const;

export type InspectorScopeBadgeLabel =
  (typeof INSPECTOR_SCOPE_BADGES)[keyof typeof INSPECTOR_SCOPE_BADGES];

const TITLE_SCOPE_BADGE: Record<string, InspectorScopeBadgeLabel> = {
  Preview: INSPECTOR_SCOPE_BADGES.preview,
  Appearance: INSPECTOR_SCOPE_BADGES.style,
  "LED appearance": INSPECTOR_SCOPE_BADGES.style,
  "Bar layout": INSPECTOR_SCOPE_BADGES.layout,
  Display: INSPECTOR_SCOPE_BADGES.display,
  "Scale & readout": INSPECTOR_SCOPE_BADGES.display,
  Readout: INSPECTOR_SCOPE_BADGES.display,
  "Trend line": INSPECTOR_SCOPE_BADGES.display,
  "Y axis": INSPECTOR_SCOPE_BADGES.display,
  "Zones & alarms": INSPECTOR_SCOPE_BADGES.zones,
  Inputs: INSPECTOR_SCOPE_BADGES.pins,
  Outputs: INSPECTOR_SCOPE_BADGES.pins,
  "Range inputs": INSPECTOR_SCOPE_BADGES.pins,
  Channels: INSPECTOR_SCOPE_BADGES.pins,
  "Monitor mode": INSPECTOR_SCOPE_BADGES.monitor,
  Capture: INSPECTOR_SCOPE_BADGES.runtime,
  Engine: INSPECTOR_SCOPE_BADGES.runtime,
  Playback: INSPECTOR_SCOPE_BADGES.runtime,
  Source: INSPECTOR_SCOPE_BADGES.runtime,
  Acquisition: INSPECTOR_SCOPE_BADGES.runtime,
  Analyser: INSPECTOR_SCOPE_BADGES.analyser,
  "Noise gate": INSPECTOR_SCOPE_BADGES.config,
  Level: INSPECTOR_SCOPE_BADGES.config,
  Tone: INSPECTOR_SCOPE_BADGES.config,
  Sweep: INSPECTOR_SCOPE_BADGES.config,
  Threshold: INSPECTOR_SCOPE_BADGES.config,
  Setpoint: INSPECTOR_SCOPE_BADGES.config,
  Math: INSPECTOR_SCOPE_BADGES.config,
  Compare: INSPECTOR_SCOPE_BADGES.config,
  Clamp: INSPECTOR_SCOPE_BADGES.config,
  Normalize: INSPECTOR_SCOPE_BADGES.config,
  Multiplexer: INSPECTOR_SCOPE_BADGES.config,
  "Logic gate": INSPECTOR_SCOPE_BADGES.config,
  "Map range": INSPECTOR_SCOPE_BADGES.config,
  Value: INSPECTOR_SCOPE_BADGES.config,
  Limits: INSPECTOR_SCOPE_BADGES.config,
  "Euler mapping": INSPECTOR_SCOPE_BADGES.config,
  "Vector Add / Subtract": INSPECTOR_SCOPE_BADGES.config,
  "Compare Vector Length": INSPECTOR_SCOPE_BADGES.config,
  "Set boolean": INSPECTOR_SCOPE_BADGES.config,
  "Key binding": INSPECTOR_SCOPE_BADGES.binding,
  "Click binding": INSPECTOR_SCOPE_BADGES.binding,
  "Stage pick binding": INSPECTOR_SCOPE_BADGES.binding,
  "Socket rows": INSPECTOR_SCOPE_BADGES.layout,
  "Body panel": INSPECTOR_SCOPE_BADGES.layout,
  "Card size": INSPECTOR_SCOPE_BADGES.layout,
  Library: INSPECTOR_SCOPE_BADGES.graph,
  "GLB drive": INSPECTOR_SCOPE_BADGES.scene,
  "Play Animation": INSPECTOR_SCOPE_BADGES.scene,
  "Toggle Model Part": INSPECTOR_SCOPE_BADGES.scene,
  "Set Model Part": INSPECTOR_SCOPE_BADGES.scene,
  "Scene Output": INSPECTOR_SCOPE_BADGES.scene,
  Environment: INSPECTOR_SCOPE_BADGES.scene,
  "Model Source": INSPECTOR_SCOPE_BADGES.scene,
  "Hardware source": INSPECTOR_SCOPE_BADGES.scene,
  Connection: INSPECTOR_SCOPE_BADGES.scene,
  "Committed scene": INSPECTOR_SCOPE_BADGES.scene,
  "Low pass": INSPECTOR_SCOPE_BADGES.config,
  Boolean: INSPECTOR_SCOPE_BADGES.config,
};

/** Resolve a meaningful header badge from a section title when no explicit label is passed. */
export function inferInspectorScopeBadge(
  title: string,
): InspectorScopeBadgeLabel | undefined {
  return TITLE_SCOPE_BADGE[title.trim()];
}
