import type { LucideIcon } from "lucide-react";
import {
  Activity,
  ArrowDown,
  ArrowLeftRight,
  BarChart2,
  BetweenHorizontalStart,
  Blend,
  Box,
  Camera,
  ChartSpline,
  Circle,
  CircleDot,
  CircleSlash2,
  Clapperboard,
  Compass,
  Cpu,
  Droplets,
  Gauge,
  GitBranch,
  GitCompare,
  Globe,
  Hash,
  Link,
  Magnet,
  Merge,
  Mic,
  Move,
  Orbit,
  Package,
  Palette,
  Image,
  Plug,
  RotateCw,
  ScanLine,
  Shrink,
  Split,
  Sigma,
  Clock,
  Thermometer,
  MousePointerClick,
  Keyboard,
  Square,
  ToggleLeft,
  Waves,
  Eye,
  Layers,
  MonitorPlay,
  Sparkles,
  Wind,
  Zap,
} from "lucide-react";

/** Maps `NodeCatalogEntry.icon` (kebab-style slug) → Lucide component. */
const CATALOG_LUCIDE_BY_SLUG: Record<string, LucideIcon> = {
  activity: Activity,
  box: Box,
  plug: Plug,
  cpu: Cpu,
  orbit: Orbit,
  compass: Compass,
  "arrow-down": ArrowDown,
  "arrow-left-right": ArrowLeftRight,
  "rotate-cw": RotateCw,
  gauge: Gauge,
  droplets: Droplets,
  magnet: Magnet,
  merge: Merge,
  mic: Mic,
  move: Move,
  thermometer: Thermometer,
  sigma: Sigma,
  "git-branch": GitBranch,
  "git-compare": GitCompare,
  blend: Blend,
  "between-horizontal-start": BetweenHorizontalStart,
  shrink: Shrink,
  split: Split,
  waves: Waves,
  "circle-dot": CircleDot,
  "chart-spline": ChartSpline,
  "bar-chart-2": BarChart2,
  circle: Circle,
  "circle-slash-2": CircleSlash2,
  clock: Clock,
  package: Package,
  "scan-line": ScanLine,
  "monitor-play": MonitorPlay,
  globe: Globe,
  camera: Camera,
  clapperboard: Clapperboard,
  "toggle-left": ToggleLeft,
  keyboard: Keyboard,
  "mouse-pointer-click": MousePointerClick,
  hash: Hash,
  palette: Palette,
  image: Image,
  eye: Eye,
  layers: Layers,
  sparkles: Sparkles,
  wind: Wind,
  zap: Zap,
  square: Square,
  link: Link,
};

export function getCatalogLucideIcon(slug: string): LucideIcon {
  return CATALOG_LUCIDE_BY_SLUG[slug] ?? Box;
}
