import { lazy } from "react";
import type { ChapterDefinition } from "../types";

export const eulerQuaternionChapter: ChapterDefinition = {
  id: "euler-quaternion",
  title: "Euler & Quaternion",
  subtitle: "Attitude fusion",
  icon: "Orbit",
  order: 2,
  slides: [
    {
      id: "eq-title",
      title: "Euler & Quaternion",
      subtitle: "Chapter entry",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/eq-title/notes.md?raw"),
      theory: () => import("./slides/eq-title/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-title/EqTitleSlide")),
    },
    {
      id: "eq-objectives",
      title: "Objectives",
      subtitle: "Learning goals",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/eq-objectives/notes.md?raw"),
      theory: () => import("./slides/eq-objectives/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-objectives/EqObjectivesSlide")),
    },
    {
      id: "eq-why-fusion",
      title: "Why fusion?",
      subtitle: "Gyro + accel roles",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/eq-why-fusion/notes.md?raw"),
      theory: () => import("./slides/eq-why-fusion/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-why-fusion/EqWhyFusionSlide")),
    },
    {
      id: "eq-euler-angles",
      title: "Euler angles",
      subtitle: "Roll pitch yaw",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/eq-euler-angles/notes.md?raw"),
      theory: () => import("./slides/eq-euler-angles/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-euler-angles/EqEulerAnglesSlide")),
    },
    {
      id: "eq-gimbal-lock",
      title: "Gimbal lock",
      subtitle: "Euler limitation",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/eq-gimbal-lock/notes.md?raw"),
      theory: () => import("./slides/eq-gimbal-lock/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-gimbal-lock/EqGimbalLockSlide")),
    },
    {
      id: "eq-quaternion-basics",
      title: "Quaternion basics",
      subtitle: "w x y z",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/eq-quaternion-basics/notes.md?raw"),
      theory: () => import("./slides/eq-quaternion-basics/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-quaternion-basics/EqQuaternionBasicsSlide")),
    },
    {
      id: "eq-euler-vs-quaternion",
      title: "Euler vs quaternion",
      subtitle: "When to use each",
      mode: "theory",
      section: "comparison",
      notes: () => import("./slides/eq-euler-vs-quaternion/notes.md?raw"),
      theory: () => import("./slides/eq-euler-vs-quaternion/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-euler-vs-quaternion/EqEulerVsQuaternionSlide")),
    },
    {
      id: "eq-demo-euler",
      title: "Live Euler",
      subtitle: "Mask 0x08",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/eq-demo-euler/notes.md?raw"),
      Component: lazy(() => import("./slides/eq-demo-euler/EqDemoEulerSlide")),
    },
    {
      id: "eq-demo-quaternion",
      title: "Live quaternion",
      subtitle: "Mask 0x10 + 3D",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/eq-demo-quaternion/notes.md?raw"),
      Component: lazy(() => import("./slides/eq-demo-quaternion/EqDemoQuaternionSlide")),
    },
    {
      id: "eq-fusion-wire",
      title: "Fusion on wire",
      subtitle: "SENSOR_CFG mask",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/eq-fusion-wire/notes.md?raw"),
      theory: () => import("./slides/eq-fusion-wire/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-fusion-wire/EqFusionWireSlide")),
    },
    {
      id: "eq-summary",
      title: "Summary",
      subtitle: "Next sensors",
      mode: "theory",
      section: "close",
      notes: () => import("./slides/eq-summary/notes.md?raw"),
      theory: () => import("./slides/eq-summary/theory.md?raw"),
      Component: lazy(() => import("./slides/eq-summary/EqSummarySlide")),
    },
  ],
};
