import type { DataTypeColorsConfig } from "../core/config/config-types";

export const DATA_TYPE_COLORS_DEFAULTS: DataTypeColorsConfig = {
  configVersion: 1,
  updatedAt: new Date(0).toISOString(),
  payload: {
    number: "#60A5FA",
    boolean: "#A78BFA",
    string: "#34D399",
    event: "#F59E0B",
    vector3: "#F472B6",
    quaternion: "#22D3EE",
    environment: "#86EFAC",
    camera: "#93C5FD",
    glbAnimation: "#FBBF24",
    transform: "#FB923C",
    fog: "#A78BFA",
    studioLight: "#FDE047",
    postProcessing: "#E879F9",
    contactShadows: "#C084FC",
    particleEmitter: "#FB923C",
    audioBus: "#F472B6",
    videoBus: "#38BDF8",
    videoTexture: "#2DD4BF",
    physicsScene: "#4ADE80",
    physicsCollider: "#2DD4BF",
    physicsBody: "#38BDF8",
    dashboardWidget: "#E879F9",
    dashboardTheme: "#C084FC",
    dashboardTab: "#A78BFA",
    material: "#F9A8D4",
    mesh: "#6EE7B7",
  },
};
