import type { NodeCatalogConfig } from "../core/config/config-types";
import {
  PALETTE_TEMPERATURE_ROW_LABEL,
  SENSOR_TEMPERATURE_PORT_LABEL,
} from "../core/sensor-port-labels";
import {
  DEFAULT_STUDIO_PACK_MODEL_ASSET_ID,
  DEFAULT_STUDIO_PACK_MODEL_RELATIVE_PATH,
} from "../../assets-manager/registry/default-studio-pack-model";
import { PSOC_E84_GLB_RELATIVE_PATH } from "../../bitstream-app/components/3d-rotation/shared/rotationPreviewConstants";
import { defaultFlowWireCameraV1 } from "../features/editor/nodes/camera-view/flow-wire-camera";
import { defaultFlowWireTransformV1 } from "../features/editor/nodes/transform/flow-wire-transform";
import {
  STAGE_DEFAULT_SHOW_GRID,
  stageSceneOutputDefaultScene3d,
} from "../core/stage/stage-scene-defaults";
import { defaultFlowWireEnvironmentV1 } from "../features/editor/nodes/environment/flow-wire-environment";
import {
  defaultScene3DConfig,
  type Scene3DConfigV1,
} from "../core/scene3d/scene3d-config";
import { VECTOR_QUATERNION_MATH_CATALOG_ENTRIES } from "./vector-quaternion-math-catalog.entries";

/**
 * Catalog defaults must persist a **logical** GLB path (`resolveWebviewModelAssetUrl`), not
 * `defaultScene3DConfig().model.url`, which can freeze an environment-specific absolute URL when
 * this module first evaluates (Vite dev vs VS Code webview vs packaged VSIX).
 */
function studioScene3dCatalogDefaults(): Scene3DConfigV1 {
  const base = defaultScene3DConfig();
  return {
    ...base,
    model: { ...base.model, url: PSOC_E84_GLB_RELATIVE_PATH },
  };
}

export const NODE_CATALOG_DEFAULTS: NodeCatalogConfig = {
  configVersion: 1,
  updatedAt: new Date("2026-05-05T00:00:00.000Z").toISOString(),
  payload: {
    nodes: [
      {
        id: "bmi270-input",
        category: "sensor",
        title: "BMI270",
        description:
          "Bosch BMI270: IMU vectors, temperature, fusion Euler (rad: roll, pitch, heading on x,y,z), and quaternion when published.",
        icon: "cpu",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "accel", portType: "vector3", label: "Accel (m/s²)" },
          { id: "gyro", portType: "vector3", label: "Gyro (rad/s)" },
          {
            id: "euler",
            portType: "vector3",
            label: "Euler (rad)",
          },
          {
            id: "quaternion",
            portType: "quaternion",
            label: "Quaternion",
          },
          {
            id: "temp",
            portType: "number",
            label: PALETTE_TEMPERATURE_ROW_LABEL,
          },
          { id: "samples", portType: "number", label: "Samples" },
        ],
      },
      {
        id: "bmi270-tap-quaternion",
        category: "sensor",
        title: "Quaternion",
        description: "Fusion quaternion only — same stream as the BMI270 node.",
        icon: "orbit",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "out", portType: "quaternion", label: "Quaternion" },
        ],
      },
      {
        id: "bmi270-tap-euler",
        category: "sensor",
        title: "Euler",
        description:
          "Fusion Euler vector only (rad) from the live BMI270 stream.",
        icon: "compass",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [{ id: "out", portType: "vector3", label: "Euler" }],
      },
      {
        id: "bmi270-tap-accel",
        category: "sensor",
        title: "Acceleration",
        description: "Acceleration vector (m/s²) from the live BMI270 stream.",
        icon: "arrow-down",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "out", portType: "vector3", label: "Acceleration" },
        ],
      },
      {
        id: "bmi270-tap-gyro",
        category: "sensor",
        title: "Gyroscope",
        description: "Gyro vector (rad/s) from the live BMI270 stream.",
        icon: "rotate-cw",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [{ id: "out", portType: "vector3", label: "Gyroscope" }],
      },
      {
        id: "bmi270-tap-temp",
        category: "sensor",
        title: "Temperature",
        description: "Die temperature (°C) from the live BMI270 stream.",
        icon: "thermometer",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          {
            id: "out",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
        ],
      },
      {
        id: "bmi270-tap-samples",
        category: "sensor",
        title: "Samples",
        description: "BMI270 sample counter — same stream as the BMI270 node.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [{ id: "out", portType: "number", label: "Samples" }],
      },
      {
        id: "dps368-input",
        category: "sensor",
        title: "DPS368",
        description:
          "Bosch DPS368: barometric pressure (hPa) and temperature (°C) from the live bitstream.",
        icon: "gauge",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "pressure", portType: "number", label: "Pressure (hPa)" },
          {
            id: "temp",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
          { id: "samples", portType: "number", label: "Samples" },
        ],
      },
      {
        id: "sht40-input",
        category: "sensor",
        title: "SHT40",
        description:
          "Sensirion SHT40: relative humidity (%RH) and temperature (°C) from the live bitstream.",
        icon: "droplets",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "humidity", portType: "number", label: "Humidity (%RH)" },
          {
            id: "temp",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
          { id: "samples", portType: "number", label: "Samples" },
        ],
      },
      {
        id: "bmm350-input",
        category: "sensor",
        title: "BMM350",
        description:
          "Bosch BMM350: magnetic field vector (µT) and temperature (°C) from the live bitstream.",
        icon: "magnet",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "magnetic", portType: "vector3", label: "Magnetic (µT)" },
          {
            id: "temp",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
          { id: "samples", portType: "number", label: "Samples" },
        ],
      },
      {
        id: "dps368-tap-pressure",
        category: "sensor",
        title: "Pressure",
        description:
          "DPS368 barometric pressure (hPa) only — same stream as the DPS368 node.",
        icon: "gauge",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "out", portType: "number", label: "Pressure (hPa)" },
        ],
      },
      {
        id: "dps368-tap-temp",
        category: "sensor",
        title: "Temperature",
        description:
          "DPS368 temperature (°C) only — same stream as the DPS368 node.",
        icon: "thermometer",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          {
            id: "out",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
        ],
      },
      {
        id: "dps368-tap-samples",
        category: "sensor",
        title: "Samples",
        description: "DPS368 sample counter — same stream as the DPS368 node.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [{ id: "out", portType: "number", label: "Samples" }],
      },
      {
        id: "sht40-tap-humidity",
        category: "sensor",
        title: "Humidity",
        description:
          "SHT40 relative humidity (%RH) only — same stream as the SHT40 node.",
        icon: "droplets",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "out", portType: "number", label: "Humidity (%RH)" },
        ],
      },
      {
        id: "sht40-tap-temp",
        category: "sensor",
        title: "Temperature",
        description:
          "SHT40 temperature (°C) only — same stream as the SHT40 node.",
        icon: "thermometer",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          {
            id: "out",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
        ],
      },
      {
        id: "sht40-tap-samples",
        category: "sensor",
        title: "Samples",
        description: "SHT40 sample counter — same stream as the SHT40 node.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [{ id: "out", portType: "number", label: "Samples" }],
      },
      {
        id: "bmm350-tap-magnetic",
        category: "sensor",
        title: "Magnetic",
        description:
          "BMM350 magnetic vector (µT) only — same stream as the BMM350 node.",
        icon: "magnet",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "out", portType: "vector3", label: "Magnetic (µT)" },
        ],
      },
      {
        id: "bmm350-tap-temp",
        category: "sensor",
        title: "Temperature",
        description:
          "BMM350 temperature (°C) only — same stream as the BMM350 node.",
        icon: "thermometer",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          {
            id: "out",
            portType: "number",
            label: SENSOR_TEMPERATURE_PORT_LABEL,
          },
        ],
      },
      {
        id: "bmm350-tap-samples",
        category: "sensor",
        title: "Samples",
        description: "BMM350 sample counter — same stream as the BMM350 node.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [{ id: "out", portType: "number", label: "Samples" }],
      },
      {
        // NOTE: disabled for Bitstream workflows (not needed).
        // Keeping the entry slot (instead of deleting file) to preserve config line history.
        id: "sensor-input",
        category: "input",
        title: "Sensor (numeric)",
        description:
          "Subscribe to one allowlisted numeric path from the live sensor stream (configure sourceKey).",
        icon: "circle-dot",
        defaultVisible: false,
        defaultConfig: {
          sourceKey: "bmi270.accel.x",
        },
        outputPorts: [{ id: "out", portType: "number", label: "Value" }],
      },
      {
        id: "mic-input",
        category: "audio",
        title: "Microphone",
        description:
          "Microphone input (permission-gated). Emits scalar audio features (RMS, peak, ZCR, centroid) as number wires for downstream logic and plotting.",
        icon: "mic",
        defaultVisible: true,
        defaultConfig: {
          enabled: false,
          deviceId: "default",
          fftSize: 2048,
          smoothing: 0.8,
          gateEnabled: false,
          gateThreshold: 0.02,
          peakHoldMs: 150,
        },
        outputPorts: [
          { id: "rms", portType: "number", label: "RMS" },
          { id: "peak", portType: "number", label: "Peak" },
          { id: "zcr", portType: "number", label: "ZCR" },
          { id: "centroidHz", portType: "number", label: "Centroid (Hz)" },
          { id: "active", portType: "boolean", label: "Active" },
          { id: "audio", portType: "audioBus", label: "Audio" },
        ],
      },
      {
        id: "audio-oscillator",
        category: "audio",
        title: "Oscillator",
        description:
          "Basic Web Audio oscillator for test signals. Drive Frequency/Gain with wires and gate playback with a boolean.",
        icon: "activity",
        defaultVisible: true,
        defaultConfig: {
          waveform: "sine",
          detuneCents: 0,
          freqHz: 440,
          sweepEnabled: false,
          sweepStartHz: 220,
          sweepEndHz: 880,
          sweepPeriodS: 4,
          gain: 0,
          gate: false,
        },
        inputPorts: [
          { id: "freqHz", portType: "number", label: "Freq (Hz)" },
          { id: "gain", portType: "number", label: "Gain" },
          { id: "gate", portType: "boolean", label: "Gate" },
        ],
        outputPorts: [
          { id: "level", portType: "number", label: "Level" },
          { id: "audio", portType: "audioBus", label: "Audio" },
        ],
      },
      {
        id: "audio-output",
        category: "audio",
        title: "Audio Output",
        description:
          "Route audio to the device output with a safe gain cap and optional limiter. Requires a user gesture to start audio on most platforms.",
        icon: "plug",
        defaultVisible: true,
        defaultConfig: {
          enabled: false,
          sourceMode: "auto",
          sourceNodeId: "",
          limiterEnabled: true,
          maxGain: 0.25,
          requiresUserGesture: true,
          gain: 0,
          gate: false,
        },
        inputPorts: [
          { id: "audio", portType: "audioBus", label: "Audio" },
          { id: "gain", portType: "number", label: "Gain" },
          { id: "gate", portType: "boolean", label: "Gate" },
        ],
      },
      {
        id: "audio-scope",
        category: "audio",
        title: "Audio Scope",
        description:
          "Waveform + spectrum visualization in a node card panel. Uses a canvas draw loop; avoids pushing audio buffers through flow pins.",
        icon: "waves",
        defaultVisible: true,
        defaultConfig: {
          sourceMode: "auto",
          sourceNodeId: "",
          mode: "waveform",
          fps: 30,
          fftSize: 2048,
          smoothing: 0.8,
          enabled: true,
        },
        inputPorts: [
          { id: "audio", portType: "audioBus", label: "Audio" },
          { id: "enabled", portType: "boolean", label: "Enabled" },
        ],
      },
      {
        id: "audio-file-player",
        category: "audio",
        title: "Audio File Player",
        description:
          "Play an audio file from a URL via Web Audio decode. Outputs transport state (playing/time/duration) and routes audio through Audio Output when enabled.",
        icon: "activity",
        defaultVisible: true,
        defaultConfig: {
          enabled: false,
          url: "",
          loop: false,
          gain: 0.5,
          gate: false,
        },
        inputPorts: [
          { id: "gain", portType: "number", label: "Gain" },
          { id: "gate", portType: "boolean", label: "Gate" },
        ],
        outputPorts: [
          { id: "playing", portType: "boolean", label: "Playing" },
          { id: "time", portType: "number", label: "Time (s)" },
          { id: "duration", portType: "number", label: "Duration (s)" },
          { id: "audio", portType: "audioBus", label: "Audio" },
        ],
      },
      {
        id: "number-average",
        category: "utility",
        title: "Average",
        description:
          "Average all incoming number wires (multi-connect to the input pin).",
        icon: "sigma",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [{ id: "in", portType: "number", label: "Values" }],
        outputPorts: [{ id: "out", portType: "number", label: "Average" }],
      },
      {
        id: "math",
        category: "utility",
        title: "Math",
        description:
          "Binary and unary float math on wired inputs A and B. Unwired inputs count as 0. sin/cos use radians.",
        icon: "zap",
        defaultVisible: true,
        defaultConfig: {
          operation: "add",
        },
        inputPorts: [
          { id: "a", portType: "number", label: "A" },
          { id: "b", portType: "number", label: "B" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "compare",
        category: "logic",
        title: "Compare",
        description:
          "Compare wired A and B with >, <, >=, <=, ==, !=. Unwired inputs count as 0. Boolean output on Out.",
        icon: "git-compare",
        defaultVisible: true,
        defaultConfig: {
          operation: ">",
        },
        inputPorts: [
          { id: "a", portType: "number", label: "A" },
          { id: "b", portType: "number", label: "B" },
        ],
        outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
      },
      {
        id: "lerp",
        category: "utility",
        title: "Scalar Lerp",
        description:
          "Scalar linear interpolation: A + (B − A) × Factor. Factor clamps to 0–1. Unwired defaults: A = 0, B = 1, Factor = 0. For vector3 or quaternion blending use Vector Lerp or Quaternion Slerp.",
        icon: "blend",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [
          { id: "a", portType: "number", label: "A" },
          { id: "b", portType: "number", label: "B" },
          { id: "t", portType: "number", label: "Factor" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "switch",
        category: "logic",
        title: "Switch",
        description:
          "When Condition is true, pass If True to Out; otherwise If False. Unwired numbers count as 0.",
        icon: "toggle-left",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [
          { id: "condition", portType: "boolean", label: "Condition" },
          { id: "ifTrue", portType: "number", label: "If True" },
          { id: "ifFalse", portType: "number", label: "If False" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "combine-xyz",
        category: "utility",
        title: "Combine Vector",
        description:
          "Build a vector3 from wired X, Y, and Z numbers. Unwired inputs count as 0.",
        icon: "merge",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "vector3", label: "Vector" }],
      },
      {
        id: "combine-quaternion",
        category: "utility",
        title: "Combine Quaternion",
        description:
          "Build a quaternion from wired W, X, Y, and Z numbers. Unwired inputs count as 0.",
        icon: "merge",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [
          { id: "w", portType: "number", label: "W" },
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "quaternion", label: "Quaternion" }],
      },
      {
        id: "logic-gate",
        category: "logic",
        title: "Logic Gate",
        description:
          "Boolean AND, OR, NOT, or XOR on inputs A and B. Numbers > 0.5 count as true. NOT uses A only.",
        icon: "toggle-left",
        defaultVisible: true,
        defaultConfig: {
          operation: "and",
        },
        inputPorts: [
          { id: "a", portType: "boolean", label: "A" },
          { id: "b", portType: "boolean", label: "B" },
        ],
        outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
      },
      {
        id: "multiplexer",
        category: "utility",
        title: "Multiplexer",
        description:
          "Extract numeric fields from a JSON payload using dot paths on outputs A, B, and C. Missing paths output 0.",
        icon: "split",
        defaultVisible: false,
        defaultConfig: {
          paths: { a: "a", b: "b", c: "c" },
        },
        inputPorts: [{ id: "payload", portType: "string", label: "Payload" }],
        outputPorts: [
          { id: "a", portType: "number", label: "A" },
          { id: "b", portType: "number", label: "B" },
          { id: "c", portType: "number", label: "C" },
        ],
      },
      {
        id: "value-normalizer",
        category: "utility",
        title: "Normalize",
        description:
          "Map Value from input domain [In min, In max] to output domain [Out min, Out max] with clamp. Wired pins override defaults.",
        icon: "arrow-left-right",
        defaultVisible: false,
        defaultConfig: {
          inMin: 0,
          inMax: 1,
          outMin: 0,
          outMax: 1,
        },
        inputPorts: [
          { id: "value", portType: "number", label: "Value" },
          { id: "inMin", portType: "number", label: "In min" },
          { id: "inMax", portType: "number", label: "In max" },
          { id: "outMin", portType: "number", label: "Out min" },
          { id: "outMax", portType: "number", label: "Out max" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "vector-splitter",
        category: "utility",
        title: "Split Vector",
        description: "Break a vector3 wire into X, Y, and Z number outputs.",
        icon: "split",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [{ id: "in", portType: "vector3", label: "Vector" }],
        outputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
      },
      {
        id: "quaternion-splitter",
        category: "utility",
        title: "Split Quaternion",
        description: "Break a quaternion wire into W, X, Y, and Z number outputs.",
        icon: "split",
        defaultVisible: true,
        defaultConfig: {},
        inputPorts: [{ id: "in", portType: "quaternion", label: "Quaternion" }],
        outputPorts: [
          { id: "w", portType: "number", label: "W" },
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
      },
      ...VECTOR_QUATERNION_MATH_CATALOG_ENTRIES,
      {
        id: "model-select",
        category: "utility",
        title: "Studio Model",
        description:
          "GLB from the Asset Browser or catalog dropdown. Drag a model from Asset Browser onto the canvas to spawn this node. Wire **Model** into a Model Viewer (or 3D Rotation) input.",
        icon: "package",
        defaultVisible: true,
        defaultConfig: {
          selectedStudioAssetId: DEFAULT_STUDIO_PACK_MODEL_ASSET_ID,
          selectedModelUrl: DEFAULT_STUDIO_PACK_MODEL_RELATIVE_PATH,
          generatedChildNodeIds: [],
        },
        outputPorts: [{ id: "out", portType: "string", label: "Model" }],
      },
      {
        id: "environment",
        category: "utility",
        title: "Environment",
        description:
          "Author cubemap / HDRI, background, and IBL settings once. Wire the output into the **Environment** input on 3D Rotation or Model Viewer nodes to override their saved scene environment while connected. Optional **boolean / number** inputs (exposed per pin in the inspector) let other nodes drive Use IBL, background texture, IBL strength, IBL-off fraction, and environment yaw; a connected wire overrides the on-card control for that field.",
        icon: "globe",
        defaultVisible: true,
        defaultConfig: {
          ...(defaultFlowWireEnvironmentV1() as unknown as Record<
            string,
            unknown
          >),
          inputSocketVisibility: {},
        },
        outputPorts: [
          { id: "out", portType: "environment", label: "Environment" },
        ],
      },
      {
        id: "camera-view",
        category: "utility",
        title: "Camera / View",
        description:
          "Author FOV, camera position, look-at target, and orbit distance limits once. Wire the output into the **Camera** input on Model Viewer or 3D Rotation nodes to override their saved scene camera while connected.",
        icon: "camera",
        defaultVisible: true,
        defaultConfig: {
          ...(defaultFlowWireCameraV1() as unknown as Record<string, unknown>),
        },
        outputPorts: [{ id: "out", portType: "camera", label: "Camera" }],
      },
      {
        id: "object-transform",
        category: "utility",
        title: "Object Transform",
        description:
          "Author model position, rotation (degrees), and scale once. Wire the output into the **Transform** input on Model Viewer or 3D Rotation nodes to override their saved scene transform while connected.",
        icon: "box",
        defaultVisible: true,
        defaultConfig: {
          ...(defaultFlowWireTransformV1() as unknown as Record<
            string,
            unknown
          >),
        },
        outputPorts: [{ id: "out", portType: "transform", label: "Transform" }],
      },
      {
        id: "transform-from-euler",
        category: "utility",
        title: "Transform from Euler",
        description:
          "Convert a **vector3** Euler wire (radians: roll, pitch, heading) into a **Transform** wire for Model Viewer / 3D Rotation **Transform** inputs. Choose **IMU / fusion** or **literal scene XYZ** mapping on the Node tab. Position and scale stay at defaults unless you chain through **Object Transform**.",
        icon: "rotate-cw",
        defaultVisible: false,
        defaultConfig: {
          eulerMapping: "fusion",
        },
        inputPorts: [{ id: "in", portType: "vector3", label: "Euler" }],
        outputPorts: [{ id: "out", portType: "transform", label: "Transform" }],
      },
      {
        id: "glb-animation-bundle",
        category: "utility",
        title: "GLB Animation Bundle",
        description:
          "Drive GLB animation clips with a structured wire. When the node is linked to the same Model as your viewer (add from palette with Model selected), the inspector lists clip names from the GLB — toggle each clip and set time (s) and speed without JSON. Wire out into **Model Viewer** or **3D Rotation** **Animation**. Optional Advanced section edits raw clips JSON.",
        icon: "clapperboard",
        defaultVisible: false,
        defaultConfig: {
          clips: {},
          animationPlaybackMode: "per-clip",
          animationBlendCompactView: true,
          animationCrossfadeS: 0.3,
        },
        outputPorts: [
          { id: "out", portType: "glbAnimation", label: "Animation" },
        ],
      },
      {
        id: "map-range",
        category: "transform",
        title: "Map Range",
        description:
          "Map Value from input domain to output domain. Wired pins override defaults. Optional clamp to output range.",
        icon: "between-horizontal-start",
        defaultVisible: true,
        defaultConfig: {
          value: 0,
          inMin: 0,
          inMax: 1,
          outMin: -1,
          outMax: 1,
          clamp: true,
        },
        inputPorts: [
          { id: "value", portType: "number", label: "Value" },
          { id: "inMin", portType: "number", label: "From min" },
          { id: "inMax", portType: "number", label: "From max" },
          { id: "outMin", portType: "number", label: "To min" },
          { id: "outMax", portType: "number", label: "To max" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "material-mix",
        category: "transform",
        title: "Material Mix",
        description:
          "Blend two numeric inputs with a factor (shader-graph primitive). Wire **Out** into **GLB Material Param** **Value** to drive animated PBR channels.",
        icon: "between-horizontal-start",
        defaultVisible: false,
        defaultConfig: {
          factor: 0.5,
        },
        inputPorts: [
          { id: "a", portType: "number", label: "A" },
          { id: "b", portType: "number", label: "B" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "clamp",
        category: "transform",
        title: "Clamp",
        description:
          "Clamp Value to [Min, Max]. Wired pins override defaults on the node card.",
        icon: "shrink",
        defaultVisible: true,
        defaultConfig: {
          value: 0,
          min: -1,
          max: 1,
        },
        inputPorts: [
          { id: "value", portType: "number", label: "Value" },
          { id: "min", portType: "number", label: "Min" },
          { id: "max", portType: "number", label: "Max" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "low-pass",
        category: "transform",
        title: "Low Pass",
        description: "Smooth incoming value using alpha blending.",
        icon: "waves",
        defaultVisible: true,
        defaultConfig: {
          alpha: 0.2,
        },
        inputPorts: [{ id: "in", portType: "number", label: "Value" }],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "on-click",
        category: "logic",
        title: "On Click",
        description:
          "Emit an **event** pulse when you click empty canvas space (not on a node). Choose left or right click on the **Node** tab. Wire into **Set Boolean**, **Toggle Boolean**, or future actions.",
        icon: "mouse-pointer-click",
        defaultVisible: true,
        defaultConfig: {
          button: "left",
        },
        outputPorts: [{ id: "out", portType: "event", label: "Click" }],
      },
      {
        id: "on-stage-pick",
        category: "logic",
        title: "On Stage Pick",
        description:
          "Emit an **event** pulse when you pick a model in the **Stage** workbench viewport (Domain C). Updates Stage focus to the picked instance. Wire into **Set Boolean**, **Toggle Boolean**, or GLB actions.",
        icon: "scan-line",
        defaultVisible: true,
        defaultConfig: {
          button: "left",
        },
        outputPorts: [{ id: "out", portType: "event", label: "Pick" }],
      },
      {
        id: "event-set-boolean",
        category: "logic",
        title: "Set Boolean",
        description:
          "On each incoming **event** pulse, set the boolean **out** wire to a configured ON/OFF value (does not flip). Wire into **Indicator** or other boolean consumers.",
        icon: "toggle-left",
        defaultVisible: true,
        defaultConfig: {
          setTo: true,
          value: false,
        },
        inputPorts: [{ id: "in", portType: "event", label: "Trigger" }],
        outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
      },
      {
        id: "on-key",
        category: "logic",
        title: "On Key",
        description:
          "Emit an **event** pulse when a keyboard key is pressed while the canvas has focus. Wire into **Toggle Boolean** or future action nodes. Configure the key on the **Node** tab.",
        icon: "keyboard",
        defaultVisible: true,
        defaultConfig: {
          key: "KeyR",
          requireCtrl: false,
          requireShift: false,
          requireAlt: false,
        },
        outputPorts: [{ id: "out", portType: "event", label: "Key down" }],
      },
      {
        id: "event-toggle-boolean",
        category: "logic",
        title: "Toggle Boolean",
        description:
          "On each incoming **event** pulse, flip the boolean **out** wire. Wire into **Indicator** or other boolean consumers.",
        icon: "toggle-left",
        defaultVisible: true,
        defaultConfig: {
          value: false,
        },
        inputPorts: [{ id: "in", portType: "event", label: "Trigger" }],
        outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
      },
      {
        id: "event-toggle-glb-part",
        category: "logic",
        title: "Toggle GLB Part",
        description:
          "On each incoming **event** pulse, flip **part** visibility for a GLB part bound from the Library **GLB** tab (0 hidden, 1 visible). Requires a linked **Model viewer** on the same Model.",
        icon: "eye",
        defaultVisible: true,
        defaultConfig: {
          value: 1,
        },
        inputPorts: [
          { id: "in", portType: "event", label: "Trigger" },
          { id: "model", portType: "string", label: "Model" },
        ],
      },
      {
        id: "event-set-glb-part",
        category: "logic",
        title: "Set GLB Part",
        description:
          "On each incoming **event** pulse, set **part** visibility to a configured visible/hidden state for a GLB part bound from the Library **GLB** tab.",
        icon: "eye",
        defaultVisible: true,
        defaultConfig: {
          setTo: 1,
          value: 0,
        },
        inputPorts: [
          { id: "in", portType: "event", label: "Trigger" },
          { id: "model", portType: "string", label: "Model" },
        ],
      },
      {
        id: "event-trigger-glb-anim",
        category: "logic",
        title: "Trigger GLB Anim",
        description:
          "On each incoming **event** pulse, restart a bound GLB **animation** clip in the **Model viewer** for the wired **Model** (default **once**). Wire **Studio Model → Model** for multi-model graphs; spawn from Library **GLB → Animations → Evt**.",
        icon: "clapperboard",
        defaultVisible: true,
        defaultConfig: {
          triggerNonce: 0,
          speed: 1,
          weight: 1,
          loopMode: "once",
        },
        inputPorts: [
          { id: "in", portType: "event", label: "Trigger" },
          { id: "model", portType: "string", label: "Model" },
        ],
      },
      {
        id: "threshold",
        category: "transform",
        title: "Threshold",
        description:
          "Compare Value against a configured threshold (boolean output).",
        icon: "gauge",
        defaultVisible: true,
        defaultConfig: {
          operator: ">",
          value: 0.5,
        },
        inputPorts: [{ id: "in", portType: "number", label: "Value" }],
        outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
      },
      {
        id: "indicator",
        category: "output",
        title: "Indicator",
        description: "Show boolean state as on/off indicator.",
        icon: "circle-dot",
        defaultVisible: true,
        defaultConfig: {
          label: "Indicator",
        },
        inputPorts: [{ id: "in", portType: "boolean", label: "On" }],
      },
      {
        id: "gauge",
        category: "output",
        title: "Gauge (legacy)",
        description:
          "Deprecated — opens as Bar Meter on load. Use Bar Meter or Radial Gauge for new graphs.",
        icon: "gauge",
        defaultVisible: false,
        defaultConfig: {
          unit: "",
          decimals: 3,
        },
        inputPorts: [{ id: "in", portType: "number", label: "Value" }],
      },
      {
        id: "sparkline",
        category: "output",
        title: "Sparkline",
        description: "Render a short trend line from incoming number values.",
        icon: "chart-spline",
        defaultVisible: true,
        defaultConfig: {
          historySize: 24,
          strokeColor: "#22d3ee",
          strokeWidth: 3,
        },
        inputPorts: [{ id: "in", portType: "number", label: "Value" }],
      },
      {
        id: "plotter",
        category: "output",
        title: "Plotter",
        description:
          "Multi-channel trend chart: one point per flow update (typically each telemetry frame). Wire scalars to Ch 1–4.",
        icon: "activity",
        defaultVisible: true,
        inputPorts: [
          { id: "ch1", portType: "number", label: "Ch 1" },
          { id: "ch2", portType: "number", label: "Ch 2" },
          { id: "ch3", portType: "number", label: "Ch 3" },
          { id: "ch4", portType: "number", label: "Ch 4" },
        ],
        defaultConfig: {
          historyLength: 256,
          verticalGain: 1,
          verticalOffset: 0,
          autoScale: true,
          yMin: -1,
          yMax: 1,
          showGrid: true,
          timeDivisions: 8,
          ampDivisions: 6,
          showLegend: true,
          channels: {
            ch1: {
              label: "Ch 1",
              visible: true,
              colorHex: "#22d3ee",
              lineStyle: "solid",
              lineWidthPx: 1.75,
              marker: "none",
              markerEvery: 8,
            },
            ch2: {
              label: "Ch 2",
              visible: true,
              colorHex: "#fbbf24",
              lineStyle: "solid",
              lineWidthPx: 1.75,
              marker: "none",
              markerEvery: 8,
            },
            ch3: {
              label: "Ch 3",
              visible: true,
              colorHex: "#34d399",
              lineStyle: "solid",
              lineWidthPx: 1.75,
              marker: "none",
              markerEvery: 8,
            },
            ch4: {
              label: "Ch 4",
              visible: true,
              colorHex: "#fb7185",
              lineStyle: "solid",
              lineWidthPx: 1.75,
              marker: "none",
              markerEvery: 8,
            },
          },
        },
      },
      {
        id: "rotation-3d-euler",
        category: "output",
        title: "3D Rotation (Euler)",
        description:
          "Preview 3D object orientation from Euler vector input (rad), using a vanilla Three.js viewport for reliable resizing. Optional **Environment**, **Camera**, **Animation**, **Transform**, **Exposure**, **Fog**, and **Studio Light** inputs override saved scene settings while connected.",
        icon: "box",
        defaultVisible: true,
        defaultConfig: {
          showGrid: true,
          scene3d: studioScene3dCatalogDefaults(),
        },
        inputPorts: [
          { id: "in", portType: "vector3", label: "Euler (rad)" },
          { id: "env", portType: "environment", label: "Environment" },
          { id: "cam", portType: "camera", label: "Camera" },
          { id: "anim", portType: "glbAnimation", label: "Animation" },
          { id: "xf", portType: "transform", label: "Transform" },
          { id: "settings", portType: "number", label: "Exposure" },
          { id: "fog", portType: "fog", label: "Fog" },
          { id: "lite", portType: "studioLight", label: "Studio Light" },
          { id: "post", portType: "postProcessing", label: "Post-FX" },
          {
            id: "cshadow",
            portType: "contactShadows",
            label: "Contact Shadows",
          },
          { id: "emitter", portType: "particleEmitter", label: "Particles" },
        ],
      },
      {
        id: "rotation-3d-quaternion",
        category: "output",
        title: "3D Rotation (Quaternion)",
        description:
          "Preview 3D object orientation from quaternion input, using a vanilla Three.js viewport for reliable resizing. Optional **Environment**, **Camera**, **Animation**, **Transform**, **Exposure**, **Fog**, and **Studio Light** inputs override saved scene settings while connected.",
        icon: "box",
        defaultVisible: true,
        defaultConfig: {
          showGrid: true,
          scene3d: studioScene3dCatalogDefaults(),
        },
        inputPorts: [
          { id: "in", portType: "quaternion", label: "Quaternion" },
          { id: "env", portType: "environment", label: "Environment" },
          { id: "cam", portType: "camera", label: "Camera" },
          { id: "anim", portType: "glbAnimation", label: "Animation" },
          { id: "xf", portType: "transform", label: "Transform" },
          { id: "settings", portType: "number", label: "Exposure" },
          { id: "fog", portType: "fog", label: "Fog" },
          { id: "lite", portType: "studioLight", label: "Studio Light" },
          { id: "post", portType: "postProcessing", label: "Post-FX" },
          {
            id: "cshadow",
            portType: "contactShadows",
            label: "Contact Shadows",
          },
          { id: "emitter", portType: "particleEmitter", label: "Particles" },
        ],
      },
      {
        id: "scene-output",
        category: "output",
        title: "Scene Output",
        description:
          "Commits wired **Models** and optional **Environment**, **Camera**, **Transform**, **Animation**, scene FX, and **Physics** to the **Stage** workbench (full Three.js + Rapier). Use **Model Viewer** on the canvas for authoring previews.",
        icon: "monitor-play",
        defaultVisible: true,
        defaultConfig: {
          showGrid: STAGE_DEFAULT_SHOW_GRID,
          scene3d: stageSceneOutputDefaultScene3d(),
        },
        inputPorts: [
          { id: "models", portType: "string", label: "Models" },
          { id: "env", portType: "environment", label: "Environment" },
          { id: "cam", portType: "camera", label: "Camera" },
          { id: "anim", portType: "glbAnimation", label: "Animation" },
          { id: "xf", portType: "transform", label: "Transform" },
          { id: "settings", portType: "number", label: "Exposure" },
          { id: "fog", portType: "fog", label: "Fog" },
          { id: "lite", portType: "studioLight", label: "Studio Light" },
          { id: "post", portType: "postProcessing", label: "Post-FX" },
          {
            id: "cshadow",
            portType: "contactShadows",
            label: "Contact Shadows",
          },
          { id: "emitter", portType: "particleEmitter", label: "Particles" },
          { id: "phys", portType: "physicsScene", label: "Physics" },
        ],
      },
      {
        id: "model-viewer",
        category: "output",
        title: "Model Viewer",
        description:
          "GLB preview in a Three.js viewport. Wire a **Studio Model** node (or Asset Browser drag) into **Model**; preview stays empty until a model URL is wired. Optional **Environment**, **Camera**, **Animation**, **Transform**, **Exposure**, **Fog**, **Studio Light**, **Post-FX**, and **Contact Shadows** inputs override saved scene settings while connected.",
        icon: "scan-line",
        defaultVisible: true,
        defaultConfig: {
          showGrid: true,
          fallbackModelUrl: "",
          scene3d: studioScene3dCatalogDefaults(),
        },
        inputPorts: [
          { id: "in", portType: "string", label: "Model" },
          { id: "env", portType: "environment", label: "Environment" },
          { id: "cam", portType: "camera", label: "Camera" },
          { id: "anim", portType: "glbAnimation", label: "Animation" },
          { id: "xf", portType: "transform", label: "Transform" },
          { id: "settings", portType: "number", label: "Exposure" },
          { id: "fog", portType: "fog", label: "Fog" },
          { id: "lite", portType: "studioLight", label: "Studio Light" },
          { id: "post", portType: "postProcessing", label: "Post-FX" },
          {
            id: "cshadow",
            portType: "contactShadows",
            label: "Contact Shadows",
          },
          { id: "emitter", portType: "particleEmitter", label: "Particles" },
          { id: "phys", portType: "physicsScene", label: "Physics" },
        ],
      },
      // ── Display / Control nodes ──────────────────────────────────────────
      {
        id: "radial-gauge",
        category: "output",
        title: "Radial Gauge",
        description:
          "Canvas arc gauge with needle, colored zones, and tick marks. Accepts a numeric input wire.",
        icon: "gauge",
        defaultVisible: true,
        defaultConfig: {
          min: 0,
          max: 100,
          unit: "",
          decimals: 1,
          zones: [
            { from: 0, to: 60, color: "#22d3ee" },
            { from: 60, to: 80, color: "#fbbf24" },
            { from: 80, to: 100, color: "#f87171" },
          ],
        },
      },
      {
        id: "bar-meter",
        category: "output",
        title: "Bar Meter",
        description:
          "Vertical or horizontal bar meter with colored zones and peak-hold marker.",
        icon: "bar-chart-2",
        defaultVisible: true,
        defaultConfig: {
          min: 0,
          max: 100,
          unit: "",
          decimals: 1,
          orientation: "vertical",
          showPeakHold: true,
          zones: [
            { from: 0, to: 60, color: "#22d3ee" },
            { from: 60, to: 80, color: "#fbbf24" },
            { from: 80, to: 100, color: "#f87171" },
          ],
        },
      },
      {
        id: "led-indicator",
        category: "output",
        title: "LED Indicator",
        description:
          "Glowing LED indicator. Boolean wire → on/off. Number wire → on when value ≥ threshold.",
        icon: "circle-dot",
        defaultVisible: true,
        defaultConfig: {
          label: "LED",
          onColor: "#22c55e",
          offColor: "#18181b",
          threshold: 0.5,
          blink: false,
        },
      },
      {
        id: "knob",
        category: "generator",
        title: "Knob",
        description:
          "Interactive rotary knob. Drag up/down or scroll to change value. Outputs a number wire.",
        icon: "circle-slash-2",
        defaultVisible: true,
        defaultConfig: {
          min: 0,
          max: 100,
          value: 50,
          step: 0,
          unit: "",
          decimals: 1,
          zones: [
            { from: 0, to: 60, color: "#22d3ee" },
            { from: 60, to: 80, color: "#fbbf24" },
            { from: 80, to: 100, color: "#f87171" },
          ],
        },
        outputPorts: [{ id: "out", portType: "number", label: "Value" }],
      },
      {
        id: "numeric-display",
        category: "output",
        title: "Numeric Display",
        description:
          "Large digital readout with optional label, unit, and zone-based color coding.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {
          label: "",
          unit: "",
          decimals: 2,
          showStatusBar: true,
          zones: [
            { from: 0, to: 60, color: "rgba(228,228,231,0.95)" },
            { from: 60, to: 80, color: "#fbbf24" },
            { from: 80, to: 100, color: "#f87171" },
          ],
        },
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "scene-time",
        category: "generator",
        title: "Scene Time",
        description:
          "Elapsed scene time in seconds and frames (30 fps frame counter).",
        icon: "clock",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "seconds", portType: "number", label: "Seconds" },
          { id: "frames", portType: "number", label: "Frames" },
        ],
      },
      {
        id: "frame-delta",
        category: "generator",
        title: "Frame Delta",
        description: "Seconds since last flow tick and instantaneous FPS.",
        icon: "gauge",
        defaultVisible: true,
        defaultConfig: {},
        outputPorts: [
          { id: "delta", portType: "number", label: "Delta" },
          { id: "fps", portType: "number", label: "FPS" },
        ],
      },
      {
        id: "debug",
        category: "generator",
        title: "Debug",
        description: "Passthrough numeric probe for inspecting wired values.",
        icon: "activity",
        defaultVisible: false,
        defaultConfig: { value: 0 },
        inputPorts: [{ id: "value", portType: "number", label: "Value" }],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "position",
        category: "utility",
        title: "Position",
        description: "Build a position vector3 from wired or default X, Y, Z.",
        icon: "move",
        defaultVisible: false,
        defaultConfig: { px: 0, py: 0, pz: 0 },
        inputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "vector3", label: "Position" }],
      },
      {
        id: "rotation",
        category: "utility",
        title: "Rotation",
        description:
          "Build a rotation vector3 (degrees) from wired or default X, Y, Z.",
        icon: "rotate-cw",
        defaultVisible: false,
        defaultConfig: { rx: 0, ry: 0, rz: 0 },
        inputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "vector3", label: "Rotation" }],
      },
      {
        id: "scale",
        category: "utility",
        title: "Scale",
        description: "Build a scale vector3 from wired or default X, Y, Z.",
        icon: "shrink",
        defaultVisible: false,
        defaultConfig: { sx: 1, sy: 1, sz: 1 },
        inputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "vector3", label: "Scale" }],
      },
      {
        id: "scene-settings",
        category: "utility",
        title: "Scene Settings",
        description: "Scene exposure value for downstream preview wiring.",
        icon: "globe",
        defaultVisible: false,
        defaultConfig: { exposure: 1 },
        inputPorts: [{ id: "exposure", portType: "number", label: "Exposure" }],
        outputPorts: [{ id: "out", portType: "number", label: "Exposure" }],
      },
      {
        id: "fog",
        category: "utility",
        title: "Fog",
        description:
          "Fog near, far, and density scalars (node-animator parity outputs).",
        icon: "waves",
        defaultVisible: false,
        defaultConfig: {
          near: 1,
          far: 50,
          density: 0.05,
          mode: "linear",
          colorHex: "#1a1a2e",
        },
        inputPorts: [
          { id: "near", portType: "number", label: "Near" },
          { id: "far", portType: "number", label: "Far" },
          { id: "density", portType: "number", label: "Density" },
        ],
        outputPorts: [
          { id: "out", portType: "fog", label: "Fog" },
          { id: "near", portType: "number", label: "Near" },
          { id: "far", portType: "number", label: "Far" },
          { id: "density", portType: "number", label: "Density" },
        ],
      },
      {
        id: "morph-target",
        category: "utility",
        title: "Morph Target",
        description:
          "Morph weight 0–1 for meshName:morphName target (node-animator parity; scene apply backlog).",
        icon: "box",
        defaultVisible: false,
        defaultConfig: { morphTargetId: "", value: 0 },
        inputPorts: [{ id: "value", portType: "number", label: "Weight" }],
        outputPorts: [{ id: "out", portType: "number", label: "Weight" }],
      },
      {
        id: "scene-light",
        category: "utility",
        title: "Light",
        description:
          "Point or directional light scalars (intensity, RGB, position).",
        icon: "zap",
        defaultVisible: false,
        defaultConfig: {
          lightType: "point",
          intensity: 1,
          r: 1,
          g: 1,
          b: 1,
          x: 0,
          y: 5,
          z: 0,
        },
        inputPorts: [
          { id: "intensity", portType: "number", label: "Intensity" },
          { id: "r", portType: "number", label: "R" },
          { id: "g", portType: "number", label: "G" },
          { id: "b", portType: "number", label: "B" },
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [
          { id: "out", portType: "studioLight", label: "Light" },
          { id: "intensity", portType: "number", label: "Intensity" },
          { id: "r", portType: "number", label: "R" },
          { id: "g", portType: "number", label: "G" },
          { id: "b", portType: "number", label: "B" },
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
      },
      {
        id: "camera-switch",
        category: "utility",
        title: "Camera Switch",
        description:
          "Active camera slot index 0–7; scoped to Model selects embedded GLB camera by sorted name.",
        icon: "clapperboard",
        defaultVisible: false,
        defaultConfig: { index: 0, cameraRig: [] as string[] },
        inputPorts: [{ id: "index", portType: "number", label: "Index" }],
        outputPorts: [{ id: "out", portType: "number", label: "Index" }],
      },
      {
        id: "post-processing",
        category: "utility",
        title: "Post-Processing",
        description:
          "Bloom intensity and threshold scalars (compositor parity outputs).",
        icon: "sparkles",
        defaultVisible: false,
        defaultConfig: {
          enableBloom: true,
          bloomIntensity: 1.5,
          bloomThreshold: 1.0,
        },
        inputPorts: [
          {
            id: "bloomIntensity",
            portType: "number",
            label: "Bloom Intensity",
          },
          {
            id: "bloomThreshold",
            portType: "number",
            label: "Bloom Threshold",
          },
        ],
        outputPorts: [
          { id: "out", portType: "postProcessing", label: "Post-FX" },
          {
            id: "bloomIntensity",
            portType: "number",
            label: "Bloom Intensity",
          },
          {
            id: "bloomThreshold",
            portType: "number",
            label: "Bloom Threshold",
          },
        ],
      },
      {
        id: "contact-shadows",
        category: "utility",
        title: "Contact Shadows",
        description:
          "Contact shadow disc for Model Viewer ground (opacity, blur, scale).",
        icon: "layers",
        defaultVisible: false,
        defaultConfig: {
          opacity: 0.5,
          blur: 2,
          far: 10,
          scale: 10,
          color: "#000000",
        },
        outputPorts: [
          { id: "out", portType: "contactShadows", label: "Contact Shadows" },
          { id: "opacity", portType: "number", label: "Opacity" },
          { id: "blur", portType: "number", label: "Blur" },
          { id: "far", portType: "number", label: "Far" },
          { id: "scale", portType: "number", label: "Scale" },
        ],
      },
      {
        id: "particle-emitter",
        category: "utility",
        title: "Particle Emitter",
        description:
          "Emitter trigger and rate scalars (preset/life on node card).",
        icon: "wind",
        defaultVisible: false,
        defaultConfig: {
          preset: "sparks",
          rate: 0,
          life: 1,
          color: "#ffaa00",
          trigger: 0,
        },
        inputPorts: [
          { id: "trigger", portType: "number", label: "Trigger" },
          { id: "rate", portType: "number", label: "Rate" },
        ],
        outputPorts: [
          { id: "out", portType: "particleEmitter", label: "Particles" },
          { id: "trigger", portType: "number", label: "Trigger" },
          { id: "rate", portType: "number", label: "Rate" },
        ],
      },
      {
        id: "uv-transform",
        category: "utility",
        title: "UV Transform",
        description:
          "UV scale, offset, and rotation scalars (material parity).",
        icon: "move",
        defaultVisible: false,
        defaultConfig: {
          uvScaleU: 1,
          uvScaleV: 1,
          uvOffsetU: 0,
          uvOffsetV: 0,
          uvRotation: 0,
        },
        inputPorts: [
          { id: "uvScaleU", portType: "number", label: "Scale U" },
          { id: "uvScaleV", portType: "number", label: "Scale V" },
          { id: "uvOffsetU", portType: "number", label: "Offset U" },
          { id: "uvOffsetV", portType: "number", label: "Offset V" },
          { id: "uvRotation", portType: "number", label: "Rotation" },
        ],
        outputPorts: [
          { id: "uvScaleU", portType: "number", label: "Scale U" },
          { id: "uvScaleV", portType: "number", label: "Scale V" },
          { id: "uvOffsetU", portType: "number", label: "Offset U" },
          { id: "uvOffsetV", portType: "number", label: "Offset V" },
          { id: "uvRotation", portType: "number", label: "Rotation" },
        ],
      },
      {
        id: "material-variant",
        category: "utility",
        title: "Material Variant",
        description:
          "GLB material variant name string (wired variant overrides card).",
        icon: "palette",
        defaultVisible: false,
        defaultConfig: { modelSourceId: "", variant: "" },
        inputPorts: [{ id: "variant", portType: "string", label: "Variant" }],
        outputPorts: [{ id: "out", portType: "string", label: "Variant" }],
      },
      {
        id: "physics-world",
        category: "utility",
        title: "Physics World",
        description:
          "Rapier world settings. Wire **Shapes** / **Bodies** from colliders and rigid bodies; wire **Scene** into Scene Output or Model Viewer **Physics**.",
        icon: "globe",
        defaultVisible: false,
        defaultConfig: { enabled: true, gravityY: -9.81 },
        inputPorts: [
          { id: "shapes", portType: "physicsCollider", label: "Shapes" },
          { id: "bodies", portType: "physicsBody", label: "Bodies" },
        ],
        outputPorts: [{ id: "out", portType: "physicsScene", label: "Scene" }],
      },
      {
        id: "rigid-body",
        category: "utility",
        title: "Rigid Body",
        description: "Dynamic rigid body — wire **Body** into Physics World **Bodies** for Rapier preview.",
        icon: "box",
        defaultVisible: false,
        defaultConfig: {
          mass: 1,
          friction: 0.5,
          restitution: 0.3,
          positionX: 0,
          positionY: 3,
          positionZ: 0,
          halfExtents: 0.25,
        },
        outputPorts: [{ id: "out", portType: "physicsBody", label: "Body" }],
      },
      {
        id: "box-collider",
        category: "utility",
        title: "Box Collider",
        description: "Static box shape — wire **Shape** into Physics World **Shapes**.",
        icon: "square",
        defaultVisible: false,
        defaultConfig: {
          positionX: 0,
          positionY: 1,
          positionZ: 0,
          rotationDegX: 0,
          rotationDegY: 0,
          rotationDegZ: 0,
          halfExtentsX: 0.5,
          halfExtentsY: 0.5,
          halfExtentsZ: 0.5,
        },
        outputPorts: [{ id: "out", portType: "physicsCollider", label: "Shape" }],
      },
      {
        id: "sphere-collider",
        category: "utility",
        title: "Sphere Collider",
        description: "Static sphere shape — wire **Shape** into Physics World **Shapes**.",
        icon: "circle",
        defaultVisible: false,
        defaultConfig: {
          positionX: 0,
          positionY: 1.2,
          positionZ: 0,
          rotationDegX: 0,
          rotationDegY: 0,
          rotationDegZ: 0,
          radius: 0.5,
        },
        outputPorts: [{ id: "out", portType: "physicsCollider", label: "Shape" }],
      },
      {
        id: "object-spawner",
        category: "utility",
        title: "Object Spawner",
        description: "Spawn mesh instances into the physics scene (Tier D1 stub).",
        icon: "sparkles",
        defaultVisible: false,
        defaultConfig: { rate: 0, maxCount: 8 },
        inputPorts: [
          { id: "trigger", portType: "number", label: "Trigger" },
          { id: "rate", portType: "number", label: "Rate" },
        ],
        outputPorts: [{ id: "spawn", portType: "event", label: "Spawn" }],
      },
      {
        id: "fixed-joint",
        category: "utility",
        title: "Fixed Joint",
        description: "Lock two rigid bodies together (Tier D1 stub).",
        icon: "link",
        defaultVisible: false,
        defaultConfig: {},
        inputPorts: [
          { id: "bodyA", portType: "transform", label: "Body A" },
          { id: "bodyB", portType: "transform", label: "Body B" },
        ],
      },
      {
        id: "hinge-joint",
        category: "utility",
        title: "Hinge Joint",
        description: "Hinge constraint between two bodies (Tier D1 stub).",
        icon: "rotate-cw",
        defaultVisible: false,
        defaultConfig: { axis: "y" },
        inputPorts: [
          { id: "bodyA", portType: "transform", label: "Body A" },
          { id: "bodyB", portType: "transform", label: "Body B" },
        ],
      },
      {
        id: "ik-chain",
        category: "utility",
        title: "IK Chain",
        description: "Inverse kinematics target stub (Tier D1).",
        icon: "move",
        defaultVisible: false,
        defaultConfig: { x: 0, y: 0, z: 0 },
        inputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
      },
      {
        id: "vector-constant",
        category: "generator",
        title: "Vector",
        description:
          "Constant vector3 from X, Y, Z. Wired axes override defaults.",
        icon: "git-branch",
        defaultVisible: true,
        defaultConfig: {
          x: 0,
          y: 0,
          z: 0,
        },
        inputPorts: [
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "vector3", label: "Vector" }],
      },
      {
        id: "quaternion-constant",
        category: "generator",
        title: "Quaternion",
        description:
          "Constant quaternion from W, X, Y, Z. Wired axes override defaults (default W = 1).",
        icon: "orbit",
        defaultVisible: true,
        defaultConfig: {
          w: 1,
          x: 0,
          y: 0,
          z: 0,
        },
        inputPorts: [
          { id: "w", portType: "number", label: "W" },
          { id: "x", portType: "number", label: "X" },
          { id: "y", portType: "number", label: "Y" },
          { id: "z", portType: "number", label: "Z" },
        ],
        outputPorts: [{ id: "out", portType: "quaternion", label: "Quaternion" }],
      },
      {
        id: "sine-wave",
        category: "generator",
        title: "Sine Wave",
        description:
          "Time-based sine generator. Wired amp/frequency/phase/offset override defaults.",
        icon: "activity",
        defaultVisible: true,
        defaultConfig: {
          frequency: 1,
          amplitude: 1,
          offset: 0,
          phase: 0,
        },
        inputPorts: [
          { id: "amplitude", portType: "number", label: "Amplitude" },
          { id: "frequency", portType: "number", label: "Frequency" },
          { id: "phase", portType: "number", label: "Phase" },
          { id: "offset", portType: "number", label: "Offset" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "ramp-sim",
        category: "generator",
        title: "Ramp",
        description: "Linear ramp over time. Optional wrap when max > min.",
        icon: "activity",
        defaultVisible: true,
        defaultConfig: {
          rate: 0.1,
          min: 0,
          max: 1,
          wrap: true,
        },
        inputPorts: [
          { id: "rate", portType: "number", label: "Rate" },
          { id: "min", portType: "number", label: "Min" },
          { id: "max", portType: "number", label: "Max" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "step-sim",
        category: "generator",
        title: "Step",
        description: "Alternates between Low and High every Interval seconds.",
        icon: "activity",
        defaultVisible: true,
        defaultConfig: {
          interval: 1,
          low: 0,
          high: 1,
        },
        inputPorts: [
          { id: "interval", portType: "number", label: "Interval" },
          { id: "low", portType: "number", label: "Low" },
          { id: "high", portType: "number", label: "High" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "noise-sim",
        category: "generator",
        title: "Noise",
        description: "Smoothed pseudo-random noise over time.",
        icon: "activity",
        defaultVisible: true,
        defaultConfig: {
          seed: 1,
          amplitude: 1,
          offset: 0,
          smooth: 0.25,
        },
        inputPorts: [
          { id: "seed", portType: "number", label: "Seed" },
          { id: "amplitude", portType: "number", label: "Amplitude" },
          { id: "offset", portType: "number", label: "Offset" },
        ],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "boolean-constant",
        category: "generator",
        title: "Boolean",
        description:
          "Fixed boolean on the **`out`** wire. Toggle on the **node card** or in the **inspector Node** tab.",
        icon: "toggle-left",
        defaultVisible: true,
        defaultConfig: {
          value: true,
        },
        outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
      },
      {
        id: "number-constant",
        category: "generator",
        title: "Number",
        description:
          "Fixed number on the **`out`** wire. Edit on the **node card** (input or slider) or in the **inspector Node** tab (same options plus min / max / step).",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {
          value: 1,
          numberMode: "float",
          cardValueControl: "input",
        },
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "float-constant",
        category: "generator",
        title: "Float",
        description:
          "Floating-point constant on the **`out`** wire. Uses the scrub field on the node card; min/max/step live in the inspector.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {
          value: 1,
          numberMode: "float",
          step: 0.01,
          cardValueControl: "input",
        },
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "integer-constant",
        category: "generator",
        title: "Integer",
        description:
          "Integer constant on the **`out`** wire. Always rounds to a whole number after clamp and step.",
        icon: "hash",
        defaultVisible: true,
        defaultConfig: {
          value: 1,
          numberMode: "integer",
          step: 1,
          cardValueControl: "input",
        },
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "glb-material-param",
        category: "generator",
        title: "GLB Material Param",
        description:
          "Drive a PBR channel (emissive, roughness, metalness, opacity) on a named GLB material. Spawn from Library **GLB → Materials** or bind `glbExtractKind: material` manually. Optional **Value** input overrides the card slider.",
        icon: "palette",
        defaultVisible: true,
        defaultConfig: {
          value: 0,
          numberMode: "float",
          cardValueControl: "input",
          glbMaterialParam: "emissive",
        },
        inputPorts: [{ id: "in", portType: "number", label: "Value" }],
        outputPorts: [{ id: "out", portType: "number", label: "Out" }],
      },
      {
        id: "glb-material-texture",
        category: "generator",
        title: "GLB Material Texture",
        description:
          "Swap a texture map (base color, normal, roughness, etc.) on a named GLB material. Spawn from Library **GLB → Materials → Tex** or bind `glbExtractKind: material` manually. Pick a 2D texture on the node card.",
        icon: "image",
        defaultVisible: true,
        defaultConfig: {
          glbMaterialTextureSlot: "map",
          textureUrl: "",
          selectedStudioTextureAssetId: "",
        },
        outputPorts: [{ id: "out", portType: "string", label: "Texture URL" }],
      },
      {
        id: "glb-material-color",
        category: "generator",
        title: "GLB Material Color",
        description:
          "Drive base or emissive **RGB** on a named GLB material. Spawn from Library **GLB → Materials → Clr** or bind manually. Optional **Color** vector3 input overrides the picker.",
        icon: "palette",
        defaultVisible: true,
        defaultConfig: {
          glbMaterialColorTarget: "baseColor",
          glbMaterialColorHex: "#ffffff",
        },
        inputPorts: [{ id: "in", portType: "vector3", label: "Color" }],
      },
    ],
  },
};
