import type { NodeCatalogEntry } from "../core/config/config-types";

/** Vector / quaternion math toolkit (flow graph utilities). */
export const VECTOR_QUATERNION_MATH_CATALOG_ENTRIES: NodeCatalogEntry[] = [
  {
    id: "vector-length",
    category: "utility",
    title: "Vector Length",
    description: "Magnitude |v| of a vector3 wire.",
    icon: "sigma",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Vector" }],
    outputPorts: [{ id: "out", portType: "number", label: "Length" }],
  },
  {
    id: "vector-length-squared",
    category: "utility",
    title: "Vector Length²",
    description: "Squared magnitude of a vector3 (faster for comparisons).",
    icon: "sigma",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Vector" }],
    outputPorts: [{ id: "out", portType: "number", label: "Length²" }],
  },
  {
    id: "vector-normalize",
    category: "utility",
    title: "Normalize Vector",
    description: "Unit vector in the same direction; zero vector when length is 0.",
    icon: "shrink",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Vector" }],
    outputPorts: [{ id: "out", portType: "vector3", label: "Unit" }],
  },
  {
    id: "vector-scale",
    category: "utility",
    title: "Vector Scale",
    description: "Multiply each component by a scalar.",
    icon: "zap",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "in", portType: "vector3", label: "Vector" },
      { id: "scale", portType: "number", label: "Scale" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Vector" }],
  },
  {
    id: "vector-add",
    category: "utility",
    title: "Vector Add",
    description: "Add or subtract two vectors (operation on Node tab).",
    icon: "zap",
    defaultVisible: true,
    defaultConfig: { operation: "add" },
    inputPorts: [
      { id: "a", portType: "vector3", label: "A" },
      { id: "b", portType: "vector3", label: "B" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Out" }],
  },
  {
    id: "vector-distance",
    category: "utility",
    title: "Vector Distance",
    description: "Distance |A − B| between two vector3 wires.",
    icon: "sigma",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "vector3", label: "A" },
      { id: "b", portType: "vector3", label: "B" },
    ],
    outputPorts: [{ id: "out", portType: "number", label: "Distance" }],
  },
  {
    id: "vector-dot",
    category: "utility",
    title: "Dot Product",
    description: "Scalar dot product A · B.",
    icon: "zap",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "vector3", label: "A" },
      { id: "b", portType: "vector3", label: "B" },
    ],
    outputPorts: [{ id: "out", portType: "number", label: "Dot" }],
  },
  {
    id: "vector-cross",
    category: "utility",
    title: "Cross Product",
    description: "Vector cross product A × B.",
    icon: "zap",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "vector3", label: "A" },
      { id: "b", portType: "vector3", label: "B" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Cross" }],
  },
  {
    id: "vector-lerp",
    category: "utility",
    title: "Vector Lerp",
    description:
      "Linear blend of vector3 A → B (vector lerp, not spherical). Factor clamps to 0–1. For rotations use Quaternion Slerp.",
    icon: "blend",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "vector3", label: "A" },
      { id: "b", portType: "vector3", label: "B" },
      { id: "t", portType: "number", label: "Factor" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Out" }],
  },
  {
    id: "vector-project",
    category: "utility",
    title: "Vector Project",
    description: "Projection of V onto Onto.",
    icon: "between-horizontal-start",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "onto", portType: "vector3", label: "Onto" },
      { id: "v", portType: "vector3", label: "V" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Project" }],
  },
  {
    id: "vector-reject",
    category: "utility",
    title: "Vector Reject",
    description: "Component of V perpendicular to Onto.",
    icon: "between-horizontal-start",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "onto", portType: "vector3", label: "Onto" },
      { id: "v", portType: "vector3", label: "V" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Reject" }],
  },
  {
    id: "vector-angle",
    category: "utility",
    title: "Angle Between Vectors",
    description: "Angle in radians between A and B (after normalization).",
    icon: "compass",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "vector3", label: "A" },
      { id: "b", portType: "vector3", label: "B" },
    ],
    outputPorts: [{ id: "out", portType: "number", label: "Radians" }],
  },
  {
    id: "compare-vector-length",
    category: "logic",
    title: "Compare Vector Length",
    description: "Compare |Vector| to Threshold (>, <, ==, etc. on Node tab).",
    icon: "git-compare",
    defaultVisible: true,
    defaultConfig: { operation: ">" },
    inputPorts: [
      { id: "in", portType: "vector3", label: "Vector" },
      { id: "threshold", portType: "number", label: "Threshold" },
    ],
    outputPorts: [{ id: "out", portType: "boolean", label: "Out" }],
  },
  {
    id: "tilt-from-accel",
    category: "utility",
    title: "Tilt from Accel",
    description:
      "Estimate roll (x) and pitch (y) radians from accelerometer vector; z = 0.",
    icon: "arrow-down",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Accel" }],
    outputPorts: [{ id: "out", portType: "vector3", label: "Euler (rad)" }],
  },
  {
    id: "euler-heading",
    category: "utility",
    title: "Euler Heading",
    description: "Heading / yaw (z) in radians from a wire Euler vector3.",
    icon: "compass",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Euler" }],
    outputPorts: [{ id: "out", portType: "number", label: "Heading" }],
  },
  {
    id: "accel-near-1g",
    category: "logic",
    title: "Accel Near 1 g",
    description: "True when |Accel| is between 9 and 10.5 m/s².",
    icon: "git-compare",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Accel" }],
    outputPorts: [{ id: "out", portType: "boolean", label: "Near 1 g" }],
  },
  {
    id: "degrees-to-radians",
    category: "utility",
    title: "Degrees to Radians",
    description: "Multiply degrees by π/180.",
    icon: "rotate-cw",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "number", label: "Degrees" }],
    outputPorts: [{ id: "out", portType: "number", label: "Radians" }],
  },
  {
    id: "radians-to-degrees",
    category: "utility",
    title: "Radians to Degrees",
    description: "Multiply radians by 180/π.",
    icon: "rotate-cw",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "number", label: "Radians" }],
    outputPorts: [{ id: "out", portType: "number", label: "Degrees" }],
  },
  {
    id: "quaternion-normalize",
    category: "utility",
    title: "Normalize Quaternion",
    description: "Unit quaternion; identity when length is 0.",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "quaternion", label: "Quaternion" }],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Unit" }],
  },
  {
    id: "quaternion-multiply",
    category: "utility",
    title: "Multiply Quaternion",
    description: "Hamilton product A × B (apply B then A in standard order).",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "quaternion", label: "A" },
      { id: "b", portType: "quaternion", label: "B" },
    ],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Out" }],
  },
  {
    id: "quaternion-conjugate",
    category: "utility",
    title: "Quaternion Conjugate",
    description: "Conjugate of the input quaternion.",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "quaternion", label: "Quaternion" }],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Conjugate" }],
  },
  {
    id: "quaternion-inverse",
    category: "utility",
    title: "Quaternion Inverse",
    description: "Inverse quaternion (conjugate for unit quaternions).",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "quaternion", label: "Quaternion" }],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Inverse" }],
  },
  {
    id: "quaternion-slerp",
    category: "utility",
    title: "Quaternion Slerp",
    description: "Spherical interpolation A → B; Factor clamps to 0–1.",
    icon: "blend",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "a", portType: "quaternion", label: "A" },
      { id: "b", portType: "quaternion", label: "B" },
      { id: "t", portType: "number", label: "Factor" },
    ],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Out" }],
  },
  {
    id: "axis-angle-to-quaternion",
    category: "utility",
    title: "Axis Angle to Quaternion",
    description: "Build quaternion from axis vector and angle in radians.",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "axis", portType: "vector3", label: "Axis" },
      { id: "angle", portType: "number", label: "Angle (rad)" },
    ],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Quaternion" }],
  },
  {
    id: "euler-to-quaternion",
    category: "utility",
    title: "Euler to Quaternion",
    description:
      "Wire Euler (x=roll, y=pitch, z=heading rad) → quaternion; intrinsic ZYX.",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "vector3", label: "Euler (rad)" }],
    outputPorts: [{ id: "out", portType: "quaternion", label: "Quaternion" }],
  },
  {
    id: "quaternion-to-euler",
    category: "utility",
    title: "Quaternion to Euler",
    description:
      "Quaternion → wire Euler (x=roll, y=pitch, z=heading rad); intrinsic ZYX.",
    icon: "orbit",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [{ id: "in", portType: "quaternion", label: "Quaternion" }],
    outputPorts: [{ id: "out", portType: "vector3", label: "Euler (rad)" }],
  },
  {
    id: "rotate-vector-by-quaternion",
    category: "utility",
    title: "Rotate Vector",
    description: "Rotate vector V by quaternion Q.",
    icon: "rotate-cw",
    defaultVisible: true,
    defaultConfig: {},
    inputPorts: [
      { id: "v", portType: "vector3", label: "Vector" },
      { id: "q", portType: "quaternion", label: "Quaternion" },
    ],
    outputPorts: [{ id: "out", portType: "vector3", label: "Rotated" }],
  },
];
