import { z } from "zod";

export const dataTypeColorsSchema = z.object({
  configVersion: z.number().int().positive(),
  updatedAt: z.string().datetime(),
  payload: z.object({
    number: z.string().min(1),
    boolean: z.string().min(1),
    string: z.string().min(1),
    event: z.string().min(1),
    vector3: z.string().min(1),
    quaternion: z.string().min(1),
    environment: z.string().min(1),
    camera: z.string().min(1).default("#93C5FD"),
    glbAnimation: z.string().min(1).default("#FBBF24"),
    transform: z.string().min(1).default("#FB923C"),
    fog: z.string().min(1).default("#A78BFA"),
    studioLight: z.string().min(1).default("#FDE047"),
    postProcessing: z.string().min(1).default("#E879F9"),
    contactShadows: z.string().min(1).default("#C084FC"),
    particleEmitter: z.string().min(1).default("#FB923C"),
    audioBus: z.string().min(1).default("#F472B6"),
    videoBus: z.string().min(1).default("#38BDF8"),
    videoTexture: z.string().min(1).default("#2DD4BF"),
    physicsScene: z.string().min(1).default("#4ADE80"),
    physicsCollider: z.string().min(1).default("#2DD4BF"),
    physicsBody: z.string().min(1).default("#38BDF8"),
    dashboardWidget: z.string().min(1).default("#E879F9"),
    dashboardTheme: z.string().min(1).default("#C084FC"),
    dashboardTab: z.string().min(1).default("#A78BFA"),
    material: z.string().min(1).default("#F9A8D4"),
    mesh: z.string().min(1).default("#6EE7B7"),
  }),
});
