#!/usr/bin/env npx tsx
/**
 * Sync portable developer kit under docs/bitstream-telemetry-provider/.
 *
 *   npm run bitstream2:telemetry-catalog:gen
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSensorCatalog } from "./catalog/sensor-catalog-source";

const HERE = dirname(fileURLToPath(import.meta.url));
const KIT_ROOT = resolve(HERE, "../../../docs/bitstream-telemetry-provider");
const CLIENT_SRC = resolve(HERE, "client/BitstreamTelemetryClient.ts");
const CLIENT_KIT = resolve(KIT_ROOT, "client/BitstreamTelemetryClient.ts");
const KIT_EXAMPLES_DIR = resolve(KIT_ROOT, "EXAMPLES");
const COURSE_TELEMETRY_EXAMPLES_DIR = resolve(
  HERE,
  "../../webview/course-studio/content/telemetry-examples",
);

const TELEMETRY_EXAMPLE_HTML_FILES = [
  ["sht40-humidity-progress-bar.html", "sht40Humidity"],
  ["dps368-pressure-progress-bar.html", "dps368Pressure"],
  ["gyro-x-progress-bar.html", "bmi270GyroX"],
] as const;

const COURSE_TELEMETRY_EXAMPLE_HTML_TS = resolve(
  HERE,
  "../../webview/course-studio/content/telemetryExampleHtml.generated.ts",
);

const CATALOG_OUTPUT_PATHS = [
  resolve(HERE, "sensor-catalog.v1.json"),
  resolve(KIT_ROOT, "sensor-catalog.v1.json"),
] as const;

const STANDALONE_CLIENT_HEADER = `/**
 * Standalone WebSocket client for ws://127.0.0.1:9997 (no repo imports).
 * Generated by npm run bitstream2:telemetry-catalog:gen — do not edit by hand.
 */

const BITSTREAM_TELEMETRY_PROVIDER_API_VERSION = 1 as const;
const BITSTREAM_TELEMETRY_PROVIDER_DEFAULT_WS_URL = "ws://127.0.0.1:9997";
const BITSTREAM_TELEMETRY_PROVIDER_EVENT = {
  CATALOG: "bitstream:catalog",
  CONFIG: "bitstream:config",
  SAMPLE: "bitstream:sample",
  HELLO: "bitstream:hello",
  CONNECTION: "bitstream:connection",
  STALE: "bitstream:stale",
  READY: "bitstream:ready",
  REQUEST: "bitstream:request",
  COMMAND: "bitstream:command",
  RESPONSE: "bitstream:response",
} as const;

type BitstreamTelemetryProviderEnvelope = {
  type: string;
  v: typeof BITSTREAM_TELEMETRY_PROVIDER_API_VERSION;
  payload: unknown;
};

type BitstreamTelemetrySensorCatalog = Record<string, unknown>;
type BitstreamTelemetryProviderConfigPayload = Record<string, unknown>;
type BitstreamTelemetryProviderSamplePayload = {
  sensor: string;
  sensorId: number;
  counter: number;
  deviceMs: number;
  hostMs: number;
  origin?: "uart" | "sim";
  mask: number;
  fields: Record<string, number>;
  units: Record<string, string>;
};

`;

function stripClientImports(source: string): string {
  return source.replace(/^import[\s\S]*?from\s+["'][^"']+["'];\r?\n/gm, "");
}

function writeCatalog(): void {
  const catalog = buildSensorCatalog();
  const json = `${JSON.stringify(catalog, null, 2)}\n`;
  for (const outPath of CATALOG_OUTPUT_PATHS) {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, json, "utf8");
    console.log(`[telemetry-kit] wrote ${outPath}`);
  }
}

function writeStandaloneClient(): void {
  const raw = readFileSync(CLIENT_SRC, "utf8");
  const body = stripClientImports(raw);
  mkdirSync(dirname(CLIENT_KIT), { recursive: true });
  writeFileSync(CLIENT_KIT, `${STANDALONE_CLIENT_HEADER}${body}`, "utf8");
  console.log(`[telemetry-kit] wrote ${CLIENT_KIT}`);
}

function writeClientReadme(): void {
  const path = resolve(KIT_ROOT, "client/README.md");
  const md = `# Telemetry provider client (standalone)

Copy \`BitstreamTelemetryClient.ts\` into external React or vanilla apps.

\`\`\`typescript
import { BitstreamTelemetryClient } from "./BitstreamTelemetryClient";

const client = new BitstreamTelemetryClient();
await client.connect();
client.on("sample", (sample) => console.log(sample.fields));
\`\`\`

Regenerate from Bitstream Studio repo:

\`\`\`bash
cd extension
npm run bitstream2:telemetry-catalog:gen
\`\`\`

See [../SDK.md](../SDK.md) for full usage.
`;
  writeFileSync(path, md, "utf8");
  console.log(`[telemetry-kit] wrote ${path}`);
}

function syncCourseTelemetryExamples(): void {
  mkdirSync(COURSE_TELEMETRY_EXAMPLES_DIR, { recursive: true });
  const generatedLines: string[] = [];
  for (const [name, exportKey] of TELEMETRY_EXAMPLE_HTML_FILES) {
    const src = resolve(KIT_EXAMPLES_DIR, name);
    const dest = resolve(COURSE_TELEMETRY_EXAMPLES_DIR, name);
    const html = readFileSync(src, "utf8");
    copyFileSync(src, dest);
    generatedLines.push(`  ${exportKey}: ${JSON.stringify(html)},`);
    console.log(`[telemetry-kit] copied example → ${dest}`);
  }
  const generated = `/** Auto-generated by npm run bitstream2:telemetry-catalog:gen — do not edit. */\nexport const TELEMETRY_EXAMPLE_HTML = {\n${generatedLines.join("\n")}\n} as const;\n`;
  writeFileSync(COURSE_TELEMETRY_EXAMPLE_HTML_TS, generated, "utf8");
  console.log(`[telemetry-kit] wrote ${COURSE_TELEMETRY_EXAMPLE_HTML_TS}`);
}

export function syncTelemetryProviderKit(): void {
  writeCatalog();
  writeStandaloneClient();
  writeClientReadme();
  syncCourseTelemetryExamples();
}

const isMain = process.argv[1] != null && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  syncTelemetryProviderKit();
}
