import { lazy } from "react";

import type { ChapterDefinition } from "../types";

export const dps368Chapter: ChapterDefinition = {
  id: "dps368",
  title: "DPS368",
  subtitle: "Barometric pressure",
  icon: "Gauge",
  order: 4,
  slides: [
    {
      id: "dps-title",
      title: "DPS368",
      subtitle: "Chapter entry",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/dps-title/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-title/DpsTitleSlide")),
    },
    {
      id: "dps-objectives",
      title: "Objectives",
      subtitle: "Learning goals",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/dps-objectives/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-objectives/DpsObjectivesSlide")),
    },
    {
      id: "dps-pressure-basics",
      title: "Pressure basics",
      subtitle: "hPa fundamentals",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/dps-pressure-basics/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-pressure-basics/DpsPressureBasicsSlide")),
    },
    {
      id: "dps-altitude",
      title: "Altitude",
      subtitle: "Barometric formula",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/dps-altitude/notes.md?raw"),
      theory: () => import("./slides/dps-altitude/theory.md?raw"),
      Component: lazy(() => import("./slides/dps-altitude/DpsAltitudeSlide")),
    },
    {
      id: "dps-product-overview",
      title: "Product overview",
      subtitle: "Datasheet snapshot",
      mode: "theory",
      section: "product",
      notes: () => import("./slides/dps-product-overview/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-product-overview/DpsProductOverviewSlide")),
    },
    {
      id: "dps-demo-pressure",
      title: "Pressure trend",
      subtitle: "Live hPa history",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/dps-demo-pressure/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-demo-pressure/DpsDemoPressureSlide")),
    },
    {
      id: "dps-demo-altitude",
      title: "Derived altitude",
      subtitle: "ISA estimate",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/dps-demo-altitude/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-demo-altitude/DpsDemoAltitudeSlide")),
    },
    {
      id: "dps-wire-mask",
      title: "Wire mask",
      subtitle: "PRESS · TMP",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/dps-wire-mask/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-wire-mask/DpsWireMaskSlide")),
    },
    {
      id: "dps-studio-node",
      title: "Sensor Studio node",
      subtitle: "Flow ports",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/dps-studio-node/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-studio-node/DpsStudioNodeSlide")),
    },
    {
      id: "dps-summary",
      title: "Summary",
      subtitle: "Next chapter",
      mode: "theory",
      section: "close",
      notes: () => import("./slides/dps-summary/notes.md?raw"),
      Component: lazy(() => import("./slides/dps-summary/DpsSummarySlide")),
    },
  ],
};
