import { lazy } from "react";

import type { ChapterDefinition } from "../types";

export const bmm350Chapter: ChapterDefinition = {
  id: "bmm350",
  title: "BMM350",
  subtitle: "Magnetometer",
  icon: "Magnet",
  order: 3,
  slides: [
    {
      id: "bmm-title",
      title: "BMM350",
      subtitle: "Chapter entry",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/bmm-title/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-title/BmmTitleSlide")),
    },
    {
      id: "bmm-objectives",
      title: "Objectives",
      subtitle: "Learning goals",
      mode: "theory",
      section: "opening",
      notes: () => import("./slides/bmm-objectives/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-objectives/BmmObjectivesSlide")),
    },
    {
      id: "bmm-earth-field",
      title: "Earth field",
      subtitle: "µT vector",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/bmm-earth-field/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-earth-field/BmmEarthFieldSlide")),
    },
    {
      id: "bmm-heading",
      title: "Heading",
      subtitle: "Level compass",
      mode: "theory",
      section: "foundations",
      notes: () => import("./slides/bmm-heading/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-heading/BmmHeadingSlide")),
    },
    {
      id: "bmm-product-overview",
      title: "Product overview",
      subtitle: "Datasheet snapshot",
      mode: "theory",
      section: "product",
      notes: () => import("./slides/bmm-product-overview/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-product-overview/BmmProductOverviewSlide")),
    },
    {
      id: "bmm-demo-vector",
      title: "Magnetic vector",
      subtitle: "Live µT",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/bmm-demo-vector/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-demo-vector/BmmDemoVectorSlide")),
    },
    {
      id: "bmm-demo-compass",
      title: "Compass heading",
      subtitle: "Rotate flat",
      mode: "demo",
      section: "demos",
      notes: () => import("./slides/bmm-demo-compass/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-demo-compass/BmmDemoCompassSlide")),
    },
    {
      id: "bmm-wire-mask",
      title: "Wire mask",
      subtitle: "MAG · TMP",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/bmm-wire-mask/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-wire-mask/BmmWireMaskSlide")),
    },
    {
      id: "bmm-studio-node",
      title: "Sensor Studio node",
      subtitle: "Flow ports",
      mode: "theory",
      section: "integration",
      notes: () => import("./slides/bmm-studio-node/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-studio-node/BmmStudioNodeSlide")),
    },
    {
      id: "bmm-summary",
      title: "Summary",
      subtitle: "Next chapter",
      mode: "theory",
      section: "close",
      notes: () => import("./slides/bmm-summary/notes.md?raw"),
      Component: lazy(() => import("./slides/bmm-summary/BmmSummarySlide")),
    },
  ],
};
